import { createFileRoute, useNavigate, redirect } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import rikkesLogo from "@/assets/rikkes-logo.png";
import { LOCAL_SESSION_KEY, getDb, initLocalDb, nowIso } from "@/lib/localDb";

export const Route = createFileRoute("/login")({ beforeLoad: async () => { if (typeof window === "undefined") return; if (!localStorage.getItem("rikkes_tni_au_local_db_v1")) initLocalDb(); if (localStorage.getItem(LOCAL_SESSION_KEY)) throw redirect({ to: "/dashboard" }); }, component: LoginPage });

function LoginPage() { const nav = useNavigate(); const [username, setUsername] = useState("admin"); const [password, setPassword] = useState("admin123"); const [loading, setLoading] = useState(false);
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); try { const u = getDb().users.find((x: any) => x.username === username && x.password === password); if (!u) throw new Error("Username/password salah"); localStorage.setItem(LOCAL_SESSION_KEY, JSON.stringify({ user_id: u.id, role: u.role, login_at: nowIso() })); toast.success("Berhasil masuk"); nav({ to: "/dashboard" }); window.setTimeout(() => { if (window.location.pathname !== "/dashboard") window.location.href = "/dashboard"; }, 150); } catch (err: any) { toast.error(err.message ?? "Terjadi kesalahan"); } finally { setLoading(false); } }
  return <div className="min-h-screen flex items-center justify-center bg-primary p-4"><div className="w-full max-w-md bg-card rounded-lg shadow-xl overflow-hidden"><div className="bg-primary text-primary-foreground px-6 py-5 border-b border-white/10 flex items-center gap-4"><img src={rikkesLogo} alt="Logo RIKKES TNI AU" width={56} height={56} className="h-14 w-14 object-contain drop-shadow" /><div><div className="text-xs tracking-widest uppercase opacity-80">Sistem Digital</div><h1 className="text-xl font-bold leading-tight">RIKKES TNI AU</h1><p className="text-xs opacity-80 mt-1">Mode Lokal (localStorage)</p></div></div><form onSubmit={submit} className="p-6 space-y-4"><div className="rounded border border-amber-500/40 bg-amber-500/10 p-2 text-xs">Gunakan fitur Backup JSON berkala agar data tidak hilang saat cache browser dibersihkan.</div><div className="space-y-1.5"><Label htmlFor="username">Username</Label><Input id="username" value={username} onChange={(e) => setUsername(e.target.value)} required /></div><div className="space-y-1.5"><Label htmlFor="password">Kata Sandi</Label><Input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></div><Button type="submit" className="w-full" disabled={loading}>{loading ? "Memproses..." : "Masuk"}</Button></form></div></div>; }
