/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management'
import { Route as AuthenticatedSopRouteImport } from './routes/_authenticated/sop'
import { Route as AuthenticatedSettingHariHRouteImport } from './routes/_authenticated/setting-hari-h'
import { Route as AuthenticatedSelectionsRouteImport } from './routes/_authenticated/selections'
import { Route as AuthenticatedRuleSimulatorRouteImport } from './routes/_authenticated/rule-simulator'
import { Route as AuthenticatedResumeCasisRouteImport } from './routes/_authenticated/resume-casis'
import { Route as AuthenticatedReleaseNotesRouteImport } from './routes/_authenticated/release-notes'
import { Route as AuthenticatedRekapAplikasiRouteImport } from './routes/_authenticated/rekap-aplikasi'
import { Route as AuthenticatedRecoveryRouteImport } from './routes/_authenticated/recovery'
import { Route as AuthenticatedQaTestCasesRouteImport } from './routes/_authenticated/qa-test-cases'
import { Route as AuthenticatedQaIssuesRouteImport } from './routes/_authenticated/qa-issues'
import { Route as AuthenticatedQaDashboardRouteImport } from './routes/_authenticated/qa-dashboard'
import { Route as AuthenticatedProgressWeightsRouteImport } from './routes/_authenticated/progress-weights'
import { Route as AuthenticatedPesertaTanpaNoTestRouteImport } from './routes/_authenticated/peserta-tanpa-no-test'
import { Route as AuthenticatedMyAnamnesisRouteImport } from './routes/_authenticated/my-anamnesis'
import { Route as AuthenticatedMedicalSubteamsRouteImport } from './routes/_authenticated/medical-subteams'
import { Route as AuthenticatedMasterJuknisRouteImport } from './routes/_authenticated/master-juknis'
import { Route as AuthenticatedLaporanTahapRouteImport } from './routes/_authenticated/laporan-tahap'
import { Route as AuthenticatedImportNomorTesRouteImport } from './routes/_authenticated/import-nomor-tes'
import { Route as AuthenticatedImportHistoryRouteImport } from './routes/_authenticated/import-history'
import { Route as AuthenticatedImportDataRouteImport } from './routes/_authenticated/import-data'
import { Route as AuthenticatedHelpCenterRouteImport } from './routes/_authenticated/help-center'
import { Route as AuthenticatedHariHRouteImport } from './routes/_authenticated/hari-h'
import { Route as AuthenticatedFormulaConfigRouteImport } from './routes/_authenticated/formula-config'
import { Route as AuthenticatedExportsRouteImport } from './routes/_authenticated/exports'
import { Route as AuthenticatedDataBelumLengkapRouteImport } from './routes/_authenticated/data-belum-lengkap'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedBypassReviewRouteImport } from './routes/_authenticated/bypass-review'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as Authenticated403RouteImport } from './routes/_authenticated/403'
import { Route as AuthenticatedSopIdRouteImport } from './routes/_authenticated/sop.$id'
import { Route as AuthenticatedSelectionsSelectionIdRouteImport } from './routes/_authenticated/selections.$selectionId'
import { Route as AuthenticatedRikkesIdRouteImport } from './routes/_authenticated/rikkes.$id'
import { Route as AuthenticatedHelpCenterSlugRouteImport } from './routes/_authenticated/help-center.$slug'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated/candidates.$id'
import { Route as AuthenticatedDashboardSeleksiSelectionIdProgressRouteImport } from './routes/_authenticated/dashboard.seleksi.$selectionId.progress'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserManagementRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSopRoute = AuthenticatedSopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingHariHRoute =
  AuthenticatedSettingHariHRouteImport.update({
    id: '/setting-hari-h',
    path: '/setting-hari-h',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSelectionsRoute = AuthenticatedSelectionsRouteImport.update({
  id: '/selections',
  path: '/selections',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRuleSimulatorRoute =
  AuthenticatedRuleSimulatorRouteImport.update({
    id: '/rule-simulator',
    path: '/rule-simulator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResumeCasisRoute =
  AuthenticatedResumeCasisRouteImport.update({
    id: '/resume-casis',
    path: '/resume-casis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReleaseNotesRoute =
  AuthenticatedReleaseNotesRouteImport.update({
    id: '/release-notes',
    path: '/release-notes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRekapAplikasiRoute =
  AuthenticatedRekapAplikasiRouteImport.update({
    id: '/rekap-aplikasi',
    path: '/rekap-aplikasi',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecoveryRoute = AuthenticatedRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQaTestCasesRoute =
  AuthenticatedQaTestCasesRouteImport.update({
    id: '/qa-test-cases',
    path: '/qa-test-cases',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQaIssuesRoute = AuthenticatedQaIssuesRouteImport.update({
  id: '/qa-issues',
  path: '/qa-issues',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQaDashboardRoute =
  AuthenticatedQaDashboardRouteImport.update({
    id: '/qa-dashboard',
    path: '/qa-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgressWeightsRoute =
  AuthenticatedProgressWeightsRouteImport.update({
    id: '/progress-weights',
    path: '/progress-weights',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPesertaTanpaNoTestRoute =
  AuthenticatedPesertaTanpaNoTestRouteImport.update({
    id: '/peserta-tanpa-no-test',
    path: '/peserta-tanpa-no-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyAnamnesisRoute =
  AuthenticatedMyAnamnesisRouteImport.update({
    id: '/my-anamnesis',
    path: '/my-anamnesis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMedicalSubteamsRoute =
  AuthenticatedMedicalSubteamsRouteImport.update({
    id: '/medical-subteams',
    path: '/medical-subteams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterJuknisRoute =
  AuthenticatedMasterJuknisRouteImport.update({
    id: '/master-juknis',
    path: '/master-juknis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLaporanTahapRoute =
  AuthenticatedLaporanTahapRouteImport.update({
    id: '/laporan-tahap',
    path: '/laporan-tahap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportNomorTesRoute =
  AuthenticatedImportNomorTesRouteImport.update({
    id: '/import-nomor-tes',
    path: '/import-nomor-tes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportHistoryRoute =
  AuthenticatedImportHistoryRouteImport.update({
    id: '/import-history',
    path: '/import-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportDataRoute = AuthenticatedImportDataRouteImport.update({
  id: '/import-data',
  path: '/import-data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpCenterRoute = AuthenticatedHelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHariHRoute = AuthenticatedHariHRouteImport.update({
  id: '/hari-h',
  path: '/hari-h',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormulaConfigRoute =
  AuthenticatedFormulaConfigRouteImport.update({
    id: '/formula-config',
    path: '/formula-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExportsRoute = AuthenticatedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDataBelumLengkapRoute =
  AuthenticatedDataBelumLengkapRouteImport.update({
    id: '/data-belum-lengkap',
    path: '/data-belum-lengkap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBypassReviewRoute =
  AuthenticatedBypassReviewRouteImport.update({
    id: '/bypass-review',
    path: '/bypass-review',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Authenticated403Route = Authenticated403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSopIdRoute = AuthenticatedSopIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSopRoute,
} as any)
const AuthenticatedSelectionsSelectionIdRoute =
  AuthenticatedSelectionsSelectionIdRouteImport.update({
    id: '/$selectionId',
    path: '/$selectionId',
    getParentRoute: () => AuthenticatedSelectionsRoute,
  } as any)
const AuthenticatedRikkesIdRoute = AuthenticatedRikkesIdRouteImport.update({
  id: '/rikkes/$id',
  path: '/rikkes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpCenterSlugRoute =
  AuthenticatedHelpCenterSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedHelpCenterRoute,
  } as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCandidatesRoute,
  } as any)
const AuthenticatedDashboardSeleksiSelectionIdProgressRoute =
  AuthenticatedDashboardSeleksiSelectionIdProgressRouteImport.update({
    id: '/seleksi/$selectionId/progress',
    path: '/seleksi/$selectionId/progress',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/403': typeof Authenticated403Route
  '/audit': typeof AuthenticatedAuditRoute
  '/bypass-review': typeof AuthenticatedBypassReviewRoute
  '/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/data-belum-lengkap': typeof AuthenticatedDataBelumLengkapRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/formula-config': typeof AuthenticatedFormulaConfigRoute
  '/hari-h': typeof AuthenticatedHariHRoute
  '/help-center': typeof AuthenticatedHelpCenterRouteWithChildren
  '/import-data': typeof AuthenticatedImportDataRoute
  '/import-history': typeof AuthenticatedImportHistoryRoute
  '/import-nomor-tes': typeof AuthenticatedImportNomorTesRoute
  '/laporan-tahap': typeof AuthenticatedLaporanTahapRoute
  '/master-juknis': typeof AuthenticatedMasterJuknisRoute
  '/medical-subteams': typeof AuthenticatedMedicalSubteamsRoute
  '/my-anamnesis': typeof AuthenticatedMyAnamnesisRoute
  '/peserta-tanpa-no-test': typeof AuthenticatedPesertaTanpaNoTestRoute
  '/progress-weights': typeof AuthenticatedProgressWeightsRoute
  '/qa-dashboard': typeof AuthenticatedQaDashboardRoute
  '/qa-issues': typeof AuthenticatedQaIssuesRoute
  '/qa-test-cases': typeof AuthenticatedQaTestCasesRoute
  '/recovery': typeof AuthenticatedRecoveryRoute
  '/rekap-aplikasi': typeof AuthenticatedRekapAplikasiRoute
  '/release-notes': typeof AuthenticatedReleaseNotesRoute
  '/resume-casis': typeof AuthenticatedResumeCasisRoute
  '/rule-simulator': typeof AuthenticatedRuleSimulatorRoute
  '/selections': typeof AuthenticatedSelectionsRouteWithChildren
  '/setting-hari-h': typeof AuthenticatedSettingHariHRoute
  '/sop': typeof AuthenticatedSopRouteWithChildren
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/help-center/$slug': typeof AuthenticatedHelpCenterSlugRoute
  '/rikkes/$id': typeof AuthenticatedRikkesIdRoute
  '/selections/$selectionId': typeof AuthenticatedSelectionsSelectionIdRoute
  '/sop/$id': typeof AuthenticatedSopIdRoute
  '/dashboard/seleksi/$selectionId/progress': typeof AuthenticatedDashboardSeleksiSelectionIdProgressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/403': typeof Authenticated403Route
  '/audit': typeof AuthenticatedAuditRoute
  '/bypass-review': typeof AuthenticatedBypassReviewRoute
  '/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/data-belum-lengkap': typeof AuthenticatedDataBelumLengkapRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/formula-config': typeof AuthenticatedFormulaConfigRoute
  '/hari-h': typeof AuthenticatedHariHRoute
  '/help-center': typeof AuthenticatedHelpCenterRouteWithChildren
  '/import-data': typeof AuthenticatedImportDataRoute
  '/import-history': typeof AuthenticatedImportHistoryRoute
  '/import-nomor-tes': typeof AuthenticatedImportNomorTesRoute
  '/laporan-tahap': typeof AuthenticatedLaporanTahapRoute
  '/master-juknis': typeof AuthenticatedMasterJuknisRoute
  '/medical-subteams': typeof AuthenticatedMedicalSubteamsRoute
  '/my-anamnesis': typeof AuthenticatedMyAnamnesisRoute
  '/peserta-tanpa-no-test': typeof AuthenticatedPesertaTanpaNoTestRoute
  '/progress-weights': typeof AuthenticatedProgressWeightsRoute
  '/qa-dashboard': typeof AuthenticatedQaDashboardRoute
  '/qa-issues': typeof AuthenticatedQaIssuesRoute
  '/qa-test-cases': typeof AuthenticatedQaTestCasesRoute
  '/recovery': typeof AuthenticatedRecoveryRoute
  '/rekap-aplikasi': typeof AuthenticatedRekapAplikasiRoute
  '/release-notes': typeof AuthenticatedReleaseNotesRoute
  '/resume-casis': typeof AuthenticatedResumeCasisRoute
  '/rule-simulator': typeof AuthenticatedRuleSimulatorRoute
  '/selections': typeof AuthenticatedSelectionsRouteWithChildren
  '/setting-hari-h': typeof AuthenticatedSettingHariHRoute
  '/sop': typeof AuthenticatedSopRouteWithChildren
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/help-center/$slug': typeof AuthenticatedHelpCenterSlugRoute
  '/rikkes/$id': typeof AuthenticatedRikkesIdRoute
  '/selections/$selectionId': typeof AuthenticatedSelectionsSelectionIdRoute
  '/sop/$id': typeof AuthenticatedSopIdRoute
  '/dashboard/seleksi/$selectionId/progress': typeof AuthenticatedDashboardSeleksiSelectionIdProgressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/403': typeof Authenticated403Route
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/bypass-review': typeof AuthenticatedBypassReviewRoute
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/data-belum-lengkap': typeof AuthenticatedDataBelumLengkapRoute
  '/_authenticated/exports': typeof AuthenticatedExportsRoute
  '/_authenticated/formula-config': typeof AuthenticatedFormulaConfigRoute
  '/_authenticated/hari-h': typeof AuthenticatedHariHRoute
  '/_authenticated/help-center': typeof AuthenticatedHelpCenterRouteWithChildren
  '/_authenticated/import-data': typeof AuthenticatedImportDataRoute
  '/_authenticated/import-history': typeof AuthenticatedImportHistoryRoute
  '/_authenticated/import-nomor-tes': typeof AuthenticatedImportNomorTesRoute
  '/_authenticated/laporan-tahap': typeof AuthenticatedLaporanTahapRoute
  '/_authenticated/master-juknis': typeof AuthenticatedMasterJuknisRoute
  '/_authenticated/medical-subteams': typeof AuthenticatedMedicalSubteamsRoute
  '/_authenticated/my-anamnesis': typeof AuthenticatedMyAnamnesisRoute
  '/_authenticated/peserta-tanpa-no-test': typeof AuthenticatedPesertaTanpaNoTestRoute
  '/_authenticated/progress-weights': typeof AuthenticatedProgressWeightsRoute
  '/_authenticated/qa-dashboard': typeof AuthenticatedQaDashboardRoute
  '/_authenticated/qa-issues': typeof AuthenticatedQaIssuesRoute
  '/_authenticated/qa-test-cases': typeof AuthenticatedQaTestCasesRoute
  '/_authenticated/recovery': typeof AuthenticatedRecoveryRoute
  '/_authenticated/rekap-aplikasi': typeof AuthenticatedRekapAplikasiRoute
  '/_authenticated/release-notes': typeof AuthenticatedReleaseNotesRoute
  '/_authenticated/resume-casis': typeof AuthenticatedResumeCasisRoute
  '/_authenticated/rule-simulator': typeof AuthenticatedRuleSimulatorRoute
  '/_authenticated/selections': typeof AuthenticatedSelectionsRouteWithChildren
  '/_authenticated/setting-hari-h': typeof AuthenticatedSettingHariHRoute
  '/_authenticated/sop': typeof AuthenticatedSopRouteWithChildren
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/_authenticated/help-center/$slug': typeof AuthenticatedHelpCenterSlugRoute
  '/_authenticated/rikkes/$id': typeof AuthenticatedRikkesIdRoute
  '/_authenticated/selections/$selectionId': typeof AuthenticatedSelectionsSelectionIdRoute
  '/_authenticated/sop/$id': typeof AuthenticatedSopIdRoute
  '/_authenticated/dashboard/seleksi/$selectionId/progress': typeof AuthenticatedDashboardSeleksiSelectionIdProgressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/403'
    | '/audit'
    | '/bypass-review'
    | '/candidates'
    | '/dashboard'
    | '/data-belum-lengkap'
    | '/exports'
    | '/formula-config'
    | '/hari-h'
    | '/help-center'
    | '/import-data'
    | '/import-history'
    | '/import-nomor-tes'
    | '/laporan-tahap'
    | '/master-juknis'
    | '/medical-subteams'
    | '/my-anamnesis'
    | '/peserta-tanpa-no-test'
    | '/progress-weights'
    | '/qa-dashboard'
    | '/qa-issues'
    | '/qa-test-cases'
    | '/recovery'
    | '/rekap-aplikasi'
    | '/release-notes'
    | '/resume-casis'
    | '/rule-simulator'
    | '/selections'
    | '/setting-hari-h'
    | '/sop'
    | '/user-management'
    | '/candidates/$id'
    | '/help-center/$slug'
    | '/rikkes/$id'
    | '/selections/$selectionId'
    | '/sop/$id'
    | '/dashboard/seleksi/$selectionId/progress'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/403'
    | '/audit'
    | '/bypass-review'
    | '/candidates'
    | '/dashboard'
    | '/data-belum-lengkap'
    | '/exports'
    | '/formula-config'
    | '/hari-h'
    | '/help-center'
    | '/import-data'
    | '/import-history'
    | '/import-nomor-tes'
    | '/laporan-tahap'
    | '/master-juknis'
    | '/medical-subteams'
    | '/my-anamnesis'
    | '/peserta-tanpa-no-test'
    | '/progress-weights'
    | '/qa-dashboard'
    | '/qa-issues'
    | '/qa-test-cases'
    | '/recovery'
    | '/rekap-aplikasi'
    | '/release-notes'
    | '/resume-casis'
    | '/rule-simulator'
    | '/selections'
    | '/setting-hari-h'
    | '/sop'
    | '/user-management'
    | '/candidates/$id'
    | '/help-center/$slug'
    | '/rikkes/$id'
    | '/selections/$selectionId'
    | '/sop/$id'
    | '/dashboard/seleksi/$selectionId/progress'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/403'
    | '/_authenticated/audit'
    | '/_authenticated/bypass-review'
    | '/_authenticated/candidates'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-belum-lengkap'
    | '/_authenticated/exports'
    | '/_authenticated/formula-config'
    | '/_authenticated/hari-h'
    | '/_authenticated/help-center'
    | '/_authenticated/import-data'
    | '/_authenticated/import-history'
    | '/_authenticated/import-nomor-tes'
    | '/_authenticated/laporan-tahap'
    | '/_authenticated/master-juknis'
    | '/_authenticated/medical-subteams'
    | '/_authenticated/my-anamnesis'
    | '/_authenticated/peserta-tanpa-no-test'
    | '/_authenticated/progress-weights'
    | '/_authenticated/qa-dashboard'
    | '/_authenticated/qa-issues'
    | '/_authenticated/qa-test-cases'
    | '/_authenticated/recovery'
    | '/_authenticated/rekap-aplikasi'
    | '/_authenticated/release-notes'
    | '/_authenticated/resume-casis'
    | '/_authenticated/rule-simulator'
    | '/_authenticated/selections'
    | '/_authenticated/setting-hari-h'
    | '/_authenticated/sop'
    | '/_authenticated/user-management'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/help-center/$slug'
    | '/_authenticated/rikkes/$id'
    | '/_authenticated/selections/$selectionId'
    | '/_authenticated/sop/$id'
    | '/_authenticated/dashboard/seleksi/$selectionId/progress'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sop': {
      id: '/_authenticated/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof AuthenticatedSopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setting-hari-h': {
      id: '/_authenticated/setting-hari-h'
      path: '/setting-hari-h'
      fullPath: '/setting-hari-h'
      preLoaderRoute: typeof AuthenticatedSettingHariHRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/selections': {
      id: '/_authenticated/selections'
      path: '/selections'
      fullPath: '/selections'
      preLoaderRoute: typeof AuthenticatedSelectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rule-simulator': {
      id: '/_authenticated/rule-simulator'
      path: '/rule-simulator'
      fullPath: '/rule-simulator'
      preLoaderRoute: typeof AuthenticatedRuleSimulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/resume-casis': {
      id: '/_authenticated/resume-casis'
      path: '/resume-casis'
      fullPath: '/resume-casis'
      preLoaderRoute: typeof AuthenticatedResumeCasisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/release-notes': {
      id: '/_authenticated/release-notes'
      path: '/release-notes'
      fullPath: '/release-notes'
      preLoaderRoute: typeof AuthenticatedReleaseNotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rekap-aplikasi': {
      id: '/_authenticated/rekap-aplikasi'
      path: '/rekap-aplikasi'
      fullPath: '/rekap-aplikasi'
      preLoaderRoute: typeof AuthenticatedRekapAplikasiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recovery': {
      id: '/_authenticated/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof AuthenticatedRecoveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa-test-cases': {
      id: '/_authenticated/qa-test-cases'
      path: '/qa-test-cases'
      fullPath: '/qa-test-cases'
      preLoaderRoute: typeof AuthenticatedQaTestCasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa-issues': {
      id: '/_authenticated/qa-issues'
      path: '/qa-issues'
      fullPath: '/qa-issues'
      preLoaderRoute: typeof AuthenticatedQaIssuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa-dashboard': {
      id: '/_authenticated/qa-dashboard'
      path: '/qa-dashboard'
      fullPath: '/qa-dashboard'
      preLoaderRoute: typeof AuthenticatedQaDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress-weights': {
      id: '/_authenticated/progress-weights'
      path: '/progress-weights'
      fullPath: '/progress-weights'
      preLoaderRoute: typeof AuthenticatedProgressWeightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/peserta-tanpa-no-test': {
      id: '/_authenticated/peserta-tanpa-no-test'
      path: '/peserta-tanpa-no-test'
      fullPath: '/peserta-tanpa-no-test'
      preLoaderRoute: typeof AuthenticatedPesertaTanpaNoTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-anamnesis': {
      id: '/_authenticated/my-anamnesis'
      path: '/my-anamnesis'
      fullPath: '/my-anamnesis'
      preLoaderRoute: typeof AuthenticatedMyAnamnesisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medical-subteams': {
      id: '/_authenticated/medical-subteams'
      path: '/medical-subteams'
      fullPath: '/medical-subteams'
      preLoaderRoute: typeof AuthenticatedMedicalSubteamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master-juknis': {
      id: '/_authenticated/master-juknis'
      path: '/master-juknis'
      fullPath: '/master-juknis'
      preLoaderRoute: typeof AuthenticatedMasterJuknisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/laporan-tahap': {
      id: '/_authenticated/laporan-tahap'
      path: '/laporan-tahap'
      fullPath: '/laporan-tahap'
      preLoaderRoute: typeof AuthenticatedLaporanTahapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import-nomor-tes': {
      id: '/_authenticated/import-nomor-tes'
      path: '/import-nomor-tes'
      fullPath: '/import-nomor-tes'
      preLoaderRoute: typeof AuthenticatedImportNomorTesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import-history': {
      id: '/_authenticated/import-history'
      path: '/import-history'
      fullPath: '/import-history'
      preLoaderRoute: typeof AuthenticatedImportHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import-data': {
      id: '/_authenticated/import-data'
      path: '/import-data'
      fullPath: '/import-data'
      preLoaderRoute: typeof AuthenticatedImportDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help-center': {
      id: '/_authenticated/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hari-h': {
      id: '/_authenticated/hari-h'
      path: '/hari-h'
      fullPath: '/hari-h'
      preLoaderRoute: typeof AuthenticatedHariHRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formula-config': {
      id: '/_authenticated/formula-config'
      path: '/formula-config'
      fullPath: '/formula-config'
      preLoaderRoute: typeof AuthenticatedFormulaConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exports': {
      id: '/_authenticated/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthenticatedExportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/data-belum-lengkap': {
      id: '/_authenticated/data-belum-lengkap'
      path: '/data-belum-lengkap'
      fullPath: '/data-belum-lengkap'
      preLoaderRoute: typeof AuthenticatedDataBelumLengkapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bypass-review': {
      id: '/_authenticated/bypass-review'
      path: '/bypass-review'
      fullPath: '/bypass-review'
      preLoaderRoute: typeof AuthenticatedBypassReviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/403': {
      id: '/_authenticated/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof Authenticated403RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sop/$id': {
      id: '/_authenticated/sop/$id'
      path: '/$id'
      fullPath: '/sop/$id'
      preLoaderRoute: typeof AuthenticatedSopIdRouteImport
      parentRoute: typeof AuthenticatedSopRoute
    }
    '/_authenticated/selections/$selectionId': {
      id: '/_authenticated/selections/$selectionId'
      path: '/$selectionId'
      fullPath: '/selections/$selectionId'
      preLoaderRoute: typeof AuthenticatedSelectionsSelectionIdRouteImport
      parentRoute: typeof AuthenticatedSelectionsRoute
    }
    '/_authenticated/rikkes/$id': {
      id: '/_authenticated/rikkes/$id'
      path: '/rikkes/$id'
      fullPath: '/rikkes/$id'
      preLoaderRoute: typeof AuthenticatedRikkesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help-center/$slug': {
      id: '/_authenticated/help-center/$slug'
      path: '/$slug'
      fullPath: '/help-center/$slug'
      preLoaderRoute: typeof AuthenticatedHelpCenterSlugRouteImport
      parentRoute: typeof AuthenticatedHelpCenterRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedCandidatesRoute
    }
    '/_authenticated/dashboard/seleksi/$selectionId/progress': {
      id: '/_authenticated/dashboard/seleksi/$selectionId/progress'
      path: '/seleksi/$selectionId/progress'
      fullPath: '/dashboard/seleksi/$selectionId/progress'
      preLoaderRoute: typeof AuthenticatedDashboardSeleksiSelectionIdProgressRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedCandidatesRouteChildren {
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
}

const AuthenticatedCandidatesRouteChildren: AuthenticatedCandidatesRouteChildren =
  {
    AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  }

const AuthenticatedCandidatesRouteWithChildren =
  AuthenticatedCandidatesRoute._addFileChildren(
    AuthenticatedCandidatesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardSeleksiSelectionIdProgressRoute: typeof AuthenticatedDashboardSeleksiSelectionIdProgressRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardSeleksiSelectionIdProgressRoute:
      AuthenticatedDashboardSeleksiSelectionIdProgressRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedHelpCenterRouteChildren {
  AuthenticatedHelpCenterSlugRoute: typeof AuthenticatedHelpCenterSlugRoute
}

const AuthenticatedHelpCenterRouteChildren: AuthenticatedHelpCenterRouteChildren =
  {
    AuthenticatedHelpCenterSlugRoute: AuthenticatedHelpCenterSlugRoute,
  }

const AuthenticatedHelpCenterRouteWithChildren =
  AuthenticatedHelpCenterRoute._addFileChildren(
    AuthenticatedHelpCenterRouteChildren,
  )

interface AuthenticatedSelectionsRouteChildren {
  AuthenticatedSelectionsSelectionIdRoute: typeof AuthenticatedSelectionsSelectionIdRoute
}

const AuthenticatedSelectionsRouteChildren: AuthenticatedSelectionsRouteChildren =
  {
    AuthenticatedSelectionsSelectionIdRoute:
      AuthenticatedSelectionsSelectionIdRoute,
  }

const AuthenticatedSelectionsRouteWithChildren =
  AuthenticatedSelectionsRoute._addFileChildren(
    AuthenticatedSelectionsRouteChildren,
  )

interface AuthenticatedSopRouteChildren {
  AuthenticatedSopIdRoute: typeof AuthenticatedSopIdRoute
}

const AuthenticatedSopRouteChildren: AuthenticatedSopRouteChildren = {
  AuthenticatedSopIdRoute: AuthenticatedSopIdRoute,
}

const AuthenticatedSopRouteWithChildren =
  AuthenticatedSopRoute._addFileChildren(AuthenticatedSopRouteChildren)

interface AuthenticatedRouteChildren {
  Authenticated403Route: typeof Authenticated403Route
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBypassReviewRoute: typeof AuthenticatedBypassReviewRoute
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDataBelumLengkapRoute: typeof AuthenticatedDataBelumLengkapRoute
  AuthenticatedExportsRoute: typeof AuthenticatedExportsRoute
  AuthenticatedFormulaConfigRoute: typeof AuthenticatedFormulaConfigRoute
  AuthenticatedHariHRoute: typeof AuthenticatedHariHRoute
  AuthenticatedHelpCenterRoute: typeof AuthenticatedHelpCenterRouteWithChildren
  AuthenticatedImportDataRoute: typeof AuthenticatedImportDataRoute
  AuthenticatedImportHistoryRoute: typeof AuthenticatedImportHistoryRoute
  AuthenticatedImportNomorTesRoute: typeof AuthenticatedImportNomorTesRoute
  AuthenticatedLaporanTahapRoute: typeof AuthenticatedLaporanTahapRoute
  AuthenticatedMasterJuknisRoute: typeof AuthenticatedMasterJuknisRoute
  AuthenticatedMedicalSubteamsRoute: typeof AuthenticatedMedicalSubteamsRoute
  AuthenticatedMyAnamnesisRoute: typeof AuthenticatedMyAnamnesisRoute
  AuthenticatedPesertaTanpaNoTestRoute: typeof AuthenticatedPesertaTanpaNoTestRoute
  AuthenticatedProgressWeightsRoute: typeof AuthenticatedProgressWeightsRoute
  AuthenticatedQaDashboardRoute: typeof AuthenticatedQaDashboardRoute
  AuthenticatedQaIssuesRoute: typeof AuthenticatedQaIssuesRoute
  AuthenticatedQaTestCasesRoute: typeof AuthenticatedQaTestCasesRoute
  AuthenticatedRecoveryRoute: typeof AuthenticatedRecoveryRoute
  AuthenticatedRekapAplikasiRoute: typeof AuthenticatedRekapAplikasiRoute
  AuthenticatedReleaseNotesRoute: typeof AuthenticatedReleaseNotesRoute
  AuthenticatedResumeCasisRoute: typeof AuthenticatedResumeCasisRoute
  AuthenticatedRuleSimulatorRoute: typeof AuthenticatedRuleSimulatorRoute
  AuthenticatedSelectionsRoute: typeof AuthenticatedSelectionsRouteWithChildren
  AuthenticatedSettingHariHRoute: typeof AuthenticatedSettingHariHRoute
  AuthenticatedSopRoute: typeof AuthenticatedSopRouteWithChildren
  AuthenticatedUserManagementRoute: typeof AuthenticatedUserManagementRoute
  AuthenticatedRikkesIdRoute: typeof AuthenticatedRikkesIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  Authenticated403Route: Authenticated403Route,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBypassReviewRoute: AuthenticatedBypassReviewRoute,
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDataBelumLengkapRoute: AuthenticatedDataBelumLengkapRoute,
  AuthenticatedExportsRoute: AuthenticatedExportsRoute,
  AuthenticatedFormulaConfigRoute: AuthenticatedFormulaConfigRoute,
  AuthenticatedHariHRoute: AuthenticatedHariHRoute,
  AuthenticatedHelpCenterRoute: AuthenticatedHelpCenterRouteWithChildren,
  AuthenticatedImportDataRoute: AuthenticatedImportDataRoute,
  AuthenticatedImportHistoryRoute: AuthenticatedImportHistoryRoute,
  AuthenticatedImportNomorTesRoute: AuthenticatedImportNomorTesRoute,
  AuthenticatedLaporanTahapRoute: AuthenticatedLaporanTahapRoute,
  AuthenticatedMasterJuknisRoute: AuthenticatedMasterJuknisRoute,
  AuthenticatedMedicalSubteamsRoute: AuthenticatedMedicalSubteamsRoute,
  AuthenticatedMyAnamnesisRoute: AuthenticatedMyAnamnesisRoute,
  AuthenticatedPesertaTanpaNoTestRoute: AuthenticatedPesertaTanpaNoTestRoute,
  AuthenticatedProgressWeightsRoute: AuthenticatedProgressWeightsRoute,
  AuthenticatedQaDashboardRoute: AuthenticatedQaDashboardRoute,
  AuthenticatedQaIssuesRoute: AuthenticatedQaIssuesRoute,
  AuthenticatedQaTestCasesRoute: AuthenticatedQaTestCasesRoute,
  AuthenticatedRecoveryRoute: AuthenticatedRecoveryRoute,
  AuthenticatedRekapAplikasiRoute: AuthenticatedRekapAplikasiRoute,
  AuthenticatedReleaseNotesRoute: AuthenticatedReleaseNotesRoute,
  AuthenticatedResumeCasisRoute: AuthenticatedResumeCasisRoute,
  AuthenticatedRuleSimulatorRoute: AuthenticatedRuleSimulatorRoute,
  AuthenticatedSelectionsRoute: AuthenticatedSelectionsRouteWithChildren,
  AuthenticatedSettingHariHRoute: AuthenticatedSettingHariHRoute,
  AuthenticatedSopRoute: AuthenticatedSopRouteWithChildren,
  AuthenticatedUserManagementRoute: AuthenticatedUserManagementRoute,
  AuthenticatedRikkesIdRoute: AuthenticatedRikkesIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
